
package GUI;

import main.Global;

/*
* made by: victorpointud
*/

public class MainMenu extends javax.swing.JFrame {

    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        settingsWindows = new Settings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfigurationButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        HPButton = new javax.swing.JButton();
        DELLButton = new javax.swing.JButton();
        BothButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConfigurationButton.setBackground(new java.awt.Color(0, 0, 0));
        ConfigurationButton.setFont(new java.awt.Font("BM Yeonsung", 1, 24)); // NOI18N
        ConfigurationButton.setForeground(new java.awt.Color(255, 255, 255));
        ConfigurationButton.setText("CONFIGURACIÓN");
        ConfigurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigurationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ConfigurationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 220, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VS_logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 280, 290));

        HPButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        HPButton.setFont(new java.awt.Font("BM Yeonsung", 1, 36)); // NOI18N
        HPButton.setText("HP");
        HPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 180));

        DELLButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        DELLButton.setFont(new java.awt.Font("BM Yeonsung", 1, 36)); // NOI18N
        DELLButton.setText("DELL");
        DELLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELLButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DELLButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 310, 180));

        BothButton.setBackground(new java.awt.Color(0, 0, 0));
        BothButton.setFont(new java.awt.Font("BM Yeonsung", 1, 36)); // NOI18N
        BothButton.setForeground(new java.awt.Color(255, 255, 255));
        BothButton.setText("DELL VS HP");
        BothButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BothButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BothButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 300, 170));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfigurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigurationButtonActionPerformed
        // TODO add your handling code here:
        settingsWindows.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ConfigurationButtonActionPerformed

    private void DELLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELLButtonActionPerformed
        GUIFunctions.openSim(1);
        Global.mainMenu.setVisible(false);
        
    }//GEN-LAST:event_DELLButtonActionPerformed

    private void BothButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BothButtonActionPerformed
         GUIFunctions.openSim(2);
         Global.mainMenu.setVisible(false);
    }//GEN-LAST:event_BothButtonActionPerformed

    private void HPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPButtonActionPerformed
         GUIFunctions.openSim(0);
         Global.mainMenu.setVisible(false);
    }//GEN-LAST:event_HPButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    private Settings settingsWindows;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BothButton;
    private javax.swing.JButton ConfigurationButton;
    private javax.swing.JButton DELLButton;
    private javax.swing.JButton HPButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
