
package GUI;

import main.Global;


/*
* made by: victorpointud
*/

public class MainMenu extends javax.swing.JFrame {

    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        settingsWindows = new Settings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BothButton = new javax.swing.JButton();
        ConfigurationButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DELLButton = new javax.swing.JButton();
        HPButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BothButton.setBackground(new java.awt.Color(0, 0, 0));
        BothButton.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        BothButton.setForeground(new java.awt.Color(255, 255, 255));
        BothButton.setText("DELL VS HP");
        BothButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BothButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BothButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 300, -1));

        ConfigurationButton.setBackground(new java.awt.Color(0, 0, 0));
        ConfigurationButton.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        ConfigurationButton.setForeground(new java.awt.Color(255, 255, 255));
        ConfigurationButton.setText("CONFIGURACIÓN");
        ConfigurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigurationButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfigurationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 370, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vs.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 550, 220));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VS_logo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 300, 300));

        DELLButton.setBackground(new java.awt.Color(0, 0, 0));
        DELLButton.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        DELLButton.setForeground(new java.awt.Color(255, 255, 255));
        DELLButton.setText("DELL");
        DELLButton.setContentAreaFilled(false);
        DELLButton.setFocusPainted(false);
        DELLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELLButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DELLButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 190, -1));

        HPButton.setBackground(new java.awt.Color(0, 0, 0));
        HPButton.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        HPButton.setForeground(new java.awt.Color(255, 255, 255));
        HPButton.setText("HP");
        HPButton.setContentAreaFilled(false);
        HPButton.setFocusPainted(false);
        HPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 180, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo-negrito.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -60, 590, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo-negrito.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 590, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfigurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigurationButtonActionPerformed
        settingsWindows.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ConfigurationButtonActionPerformed

    private void DELLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELLButtonActionPerformed
        GUIFunctions.openSim(1);
        Global.mainMenu.setVisible(false);
        
    }//GEN-LAST:event_DELLButtonActionPerformed

    private void BothButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BothButtonActionPerformed
         GUIFunctions.openSim(2);
         Global.mainMenu.setVisible(false);
    }//GEN-LAST:event_BothButtonActionPerformed

    private void HPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPButtonActionPerformed
        GUIFunctions.openSim(0);
        Global.mainMenu.setVisible(false);
    }//GEN-LAST:event_HPButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    private Settings settingsWindows;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BothButton;
    private javax.swing.JButton ConfigurationButton;
    private javax.swing.JButton DELLButton;
    private javax.swing.JButton HPButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
